// Code generated by "stringer -type BussinessType -linecomment"; DO NOT EDIT.

package rohon

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RH_TRADE_BZTP_Future-49]
	_ = x[RH_TRADE_BZTP_Stock-50]
}

const _BussinessType_name = "期货证券"

var _BussinessType_index = [...]uint8{0, 6, 12}

func (i BusinessType) String() string {
	i -= 49
	if i >= BusinessType(len(_BussinessType_index)-1) {
		return "BussinessType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _BussinessType_name[_BussinessType_index[i]:_BussinessType_index[i+1]]
}
